# Generated by Django 5.0.2 on 2024-02-26 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('description', models.CharField(max_length=165, verbose_name='Descrição')),
                ('slug', models.SlugField()),
                ('preparation_time', models.IntegerField(max_length=3, verbose_name='Tempo de prepro')),
                ('preparation_time_unit', models.CharField(max_length=5, verbose_name='Preparação tempo de unidade')),
                ('servings', models.CharField(max_length=3, verbose_name='Serve')),
                ('servings_unit', models.CharField(max_length=10, verbose_name='serve Pessoas')),
                ('preparation_step', models.CharField(max_length=165, verbose_name='Etapa de preparação')),
                ('preparation_step_is_html', models.BooleanField(default='False')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('cover', models.ImageField(upload_to='recipes/cover/%Y/%m/%d/')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.category')),
            ],
        ),
    ]
