# Generated by Django 5.0.2 on 2024-07-03 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.category'),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='cover',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='recipes/cover/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='preparation_time',
            field=models.IntegerField(verbose_name='Tempo de prepro'),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='preparation_time_unit',
            field=models.CharField(max_length=65, verbose_name='Preparação tempo de unidade'),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='servings_unit',
            field=models.CharField(max_length=65, verbose_name='serve Pessoas'),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='title',
            field=models.CharField(max_length=65),
        ),
    ]
